"""empty message

Revision ID: 801dddd85950
Revises: 4ce10df520ba
Create Date: 2024-12-17 15:48:54.437154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '801dddd85950'
down_revision = '4ce10df520ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('name')

    # ### end Alembic commands ###
